version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

install:
- ps: >-
    cd src

    nuget restore Vortice.sln
build:
  project: src/Vortice.sln
  verbosity: minimal
before_package:
- cmd: msbuild /t:pack /p:Configuration=Release core/Vortice/Vortice.csproj
- cmd: msbuild /t:pack /p:Configuration=Release engine/Vortice.Graphics/Vortice.Graphics.csproj
- cmd: msbuild /t:pack /p:Configuration=Release engine/Vortice.Audio/Vortice.Audio.csproj
- cmd: msbuild /t:pack /p:Configuration=Release engine/Vortice.Game/Vortice.Game.csproj

artifacts:
- path: bin\Packages\Release\*.nupkg
  name: Nugets Artifacts

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Nugets Artifacts
